EDGE_NUM_TO_GET_FRAME_POSE: 4
TRANSLATION_STRESS_THRESHOLD_GAIN: 1.1
ROTATION_STRESS_THRESHOLD_GAIN: 1.1

INITIAL_EDGE_DISTANCE_FROM_FRAME: 1.2
EDGE_POSE_TRANSLATE_GAIN: 0.3
EDGE_POSE_ROTATE_GAIN: 0.01
EDGE_MIN_TRANSLATE_FORCE: 0.0001
DELTA_EDGE_POSITION_TO_CHECK: 0.3
CAL_FINISH_TRANSLATE_VARIANCE: 1.0e-8
CAL_FINISH_ROTATE_VARIANCE: 1.0e-8

MAX_CAL_ITER: 2000
FRAME_POSE_TRANSLATE_GAIN: 0.5
FRAME_POSE_ROTATE_GAIN: 0.1
FRAME_POSE_CAL_FINISH_TRANSLATE_VARIANCE: 1.0e-12
FRAME_POSE_CAL_FINISH_TRANSLATIONAL_DELTA: 0.000001
FRAME_POSE_CAL_FINISH_ROTATIONAL_DELTA: 0.000001

EXTERNAL_POSITION_GAIN: 0.6
EXTERNAL_ROTATION_GAIN: 0.5

CAL_FINISH_FORCE_SIZE: 0.000015  # not used
CAL_FINISH_TORQUE_SIZE: 0.00001  # not used

