EDGE_NUM_TO_GET_FRAME_POSE: 4
TRANSLATION_STRESS_THRESHOLD_GAIN: 1.1
ROTATION_STRESS_THRESHOLD_GAIN: 1.1
INITIAL_EDGE_DISTANCE_FROM_FRAME: 1.1
EDGE_POSE_TRANSLATE_GAIN: 0.9
EDGE_POSE_ROTATE_GAIN: 0.1
DELTA_EDGE_POSITION_TO_CHECK: 0.1
MAX_CAL_ITER: 2000
FRAME_POSE_TRANSLATE_GAIN: 1.8
FRAME_POSE_ROTATE_GAIN: 0.1
CAL_FINISH_FORCE_SIZE: 0.000015
CAL_FINISH_TORQUE_SIZE: 0.00001

